/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import vista.graficador.myFrame;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        conversor_btn = new javax.swing.JButton();
        estandar_btn = new javax.swing.JButton();
        derivadas_btn = new javax.swing.JButton();
        funciones_btn = new javax.swing.JButton();
        graficadora_btn = new javax.swing.JButton();
        biseccion_btn = new javax.swing.JButton();
        regla_falsa_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadoras de todo tipo");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("CALCULADORAS DE TODO TIPO");

        conversor_btn.setText("Conversor a diferentes bases");
        conversor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversor_btnActionPerformed(evt);
            }
        });

        estandar_btn.setText("Estandar IEEE754");
        estandar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estandar_btnActionPerformed(evt);
            }
        });

        derivadas_btn.setText("Calculadora de derivadas");
        derivadas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derivadas_btnActionPerformed(evt);
            }
        });

        funciones_btn.setText("Calculadora de funciones");
        funciones_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funciones_btnActionPerformed(evt);
            }
        });

        graficadora_btn.setText("Graficadora");
        graficadora_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficadora_btnActionPerformed(evt);
            }
        });

        biseccion_btn.setText("Método de bisección");
        biseccion_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biseccion_btnActionPerformed(evt);
            }
        });

        regla_falsa_btn.setText("Método de regla falsa");
        regla_falsa_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regla_falsa_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graficadora_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(derivadas_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conversor_btn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(estandar_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(funciones_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(biseccion_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(regla_falsa_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conversor_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estandar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(biseccion_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(derivadas_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funciones_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regla_falsa_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(graficadora_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conversor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversor_btnActionPerformed
        // TODO add your handling code here:
        new Convertir().setVisible(true);
    }//GEN-LAST:event_conversor_btnActionPerformed

    private void estandar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estandar_btnActionPerformed
        // TODO add your handling code here:
        new EstandarIEEE754().setVisible(true);
    }//GEN-LAST:event_estandar_btnActionPerformed

    private void derivadas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derivadas_btnActionPerformed
        // TODO add your handling code here:
        try {
            new Derivadas().setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(Derivadas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_derivadas_btnActionPerformed

    private void funciones_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funciones_btnActionPerformed
        // TODO add your handling code here:
        new CalculadoraFunciones().setVisible(true);
    }//GEN-LAST:event_funciones_btnActionPerformed

    private void graficadora_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficadora_btnActionPerformed
        // TODO add your handling code here:
        myFrame aplicacion = new myFrame();
    }//GEN-LAST:event_graficadora_btnActionPerformed

    private void biseccion_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biseccion_btnActionPerformed
        // TODO add your handling code here:
        new MetodoBiseccion().setVisible(true);
    }//GEN-LAST:event_biseccion_btnActionPerformed

    private void regla_falsa_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regla_falsa_btnActionPerformed
        // TODO add your handling code here:
        new ReglaFalsaVista().setVisible(true);
    }//GEN-LAST:event_regla_falsa_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton biseccion_btn;
    private javax.swing.JButton conversor_btn;
    private javax.swing.JButton derivadas_btn;
    private javax.swing.JButton estandar_btn;
    private javax.swing.JButton funciones_btn;
    private javax.swing.JButton graficadora_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regla_falsa_btn;
    // End of variables declaration//GEN-END:variables
}
